#!/usr/bin/env python
"""The by-sparsity panels again -- dense / ALPS / SFT / SCOUT -- with the
dataset CoT added as a starred landmark.

Same layout as tsne_bylevel_*.png: one panel per prompt, every rollout a point.
The CoT star is drawn but excluded from the MMD numbers: OpenThoughts3 ships one
trace per problem, and an MMD against a single point has no sampling behaviour
behind it.

Bandwidth is fixed once per prompt over all models' embeddings rather than per
comparison, so the numbers share a scale.

Reads pooled.npz -- no GPU, re-renders in a couple of minutes.
"""
import argparse, json, os
import numpy as np


def mmd2(A, B, med):
    Z = np.concatenate([A, B]).astype(np.float32)
    sq = (Z * Z).sum(1)
    d2 = np.maximum(sq[:, None] + sq[None, :] - 2.0 * (Z @ Z.T), 0.0)
    K = np.exp(-d2 / med); n = len(A)
    return float(K[:n, :n].mean() + K[n:, n:].mean() - 2 * K[:n, n:].mean())


def bandwidth(arrays):
    Z = np.concatenate(arrays).astype(np.float32)
    sq = (Z * Z).sum(1)
    d2 = np.maximum(sq[:, None] + sq[None, :] - 2.0 * (Z @ Z.T), 0.0)
    return float(np.median(d2[d2 > 0]))


def embed(X, seed=0, perplexity=30):
    from sklearn.decomposition import PCA
    from sklearn.manifold import TSNE
    Xp = PCA(n_components=min(50, X.shape[1], len(X) - 1),
             random_state=seed).fit_transform(X.astype(np.float32))
    p = min(perplexity, max(5, (len(Xp) - 1) // 4))
    return TSNE(n_components=2, perplexity=p, init="pca", random_state=seed,
                max_iter=1000).fit_transform(Xp)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--states_dir", required=True)
    ap.add_argument("--layer", type=int, default=18)
    ap.add_argument("--window", default="late")
    ap.add_argument("--sparsity", default="s70")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    z = np.load(os.path.join(args.states_dir, "pooled.npz"))
    meta = json.load(open(os.path.join(args.states_dir, "pooled_meta.json")))
    P = meta["prompts"]; L, w, sp = args.layer, args.window, args.sparsity

    METHODS = [("dense", "dense"), ("ALPS", f"alps:{sp}"),
               ("SparseGPT", f"sparsegpt:{sp}"), ("SCOUT", f"ours:{sp}")]
    COL = {"dense": "#3f4652", "ALPS": "#d4772e", "SparseGPT": "#8c4a9e",
           "SCOUT": "#0f7b6c"}

    def get(pi, key):
        k = f"p{pi}|{key}|L{L}|{w}"
        return z[k].astype(np.float32) if k in z.files else None

    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.size": 9, "axes.titlesize": 9})

    fig, axes = plt.subplots(1, P, figsize=(3.3 * P, 3.9))
    axes = np.atleast_1d(axes)
    allm = {n: [] for n, _ in METHODS if n != "dense"}
    for pi in range(P):
        ax = axes[pi]
        D = get(pi, "dense")
        med = bandwidth([v for _, k in METHODS if (v := get(pi, k)) is not None])
        Xs, lab = [], []
        for nm, key in METHODS:
            v = get(pi, key)
            if v is None:
                continue
            Xs.append(v); lab += [nm] * len(v)
        T = get(pi, "teacher")
        if T is not None and len(T):
            Xs.append(T); lab += ["CoT"] * len(T)
        Z = embed(np.concatenate(Xs), args.seed)
        lab = np.array(lab)
        for nm, key in METHODS:
            m = lab == nm
            if m.any():
                ax.scatter(Z[m, 0], Z[m, 1], s=11, alpha=.70, c=COL[nm],
                           linewidths=0, label=nm,
                           zorder=4 if nm == "SCOUT" else 3)
        m = lab == "CoT"
        if m.any():
            ax.scatter(Z[m, 0], Z[m, 1], s=210, marker="*", c="#c2185b",
                       edgecolors="white", linewidths=1.0, zorder=6,
                       label="dataset CoT")
        sub = []
        for nm, key in METHODS:
            if nm == "dense":
                continue
            v = get(pi, key)
            if v is None:
                continue
            val = mmd2(D, v, med); allm[nm].append(val)
            sub.append(f"{nm} {val:.3f}")
        ax.set_title(f"prompt {pi}\nMMD$^2$ to dense:  " + "  ".join(sub),
                     fontsize=8.5)
        ax.set_xticks([]); ax.set_yticks([])
        for s in ax.spines.values():
            s.set_color("#c8cdd3")
    axes[0].legend(loc="upper left", frameon=True, framealpha=.92, fontsize=8,
                   markerscale=1.4, handletextpad=.3, borderpad=.3)
    fig.suptitle(
        f"Rollouts generated by each model at {sp[1:]}% sparsity, embedded by the "
        f"dense model (layer {L}, mean over continuation tokens "
        f"{meta['windows'][w][0]}-{meta['windows'][w][1]}). "
        f"One panel per prompt; one point per rollout. The dataset CoT is a single "
        f"trace, shown as a landmark only and excluded from MMD$^2$.",
        fontsize=9.5, y=1.02)
    fig.tight_layout()
    p = os.path.join(args.outdir, f"bylevel_{sp}_L{L}_{w}.png")
    fig.savefig(p, dpi=300, bbox_inches="tight")
    fig.savefig(p.replace(".png", ".pdf"), bbox_inches="tight")
    print(f"  {sp}: " + "  ".join(f"{n} {np.mean(v):.4f}" for n, v in allm.items()))
    print(f"  wrote {p} (+ .pdf)")


if __name__ == "__main__":
    main()
