#!/usr/bin/env python3
"""Join every run's RESULT with its local checkpoint dir and its Hub URL.

Produces ARTIFACT_INDEX.{tsv,md}: one row per trained model -- score on all
five benchmarks, the local directory, and the huggingface URL if it is
uploaded.  Re-runnable; it re-lists the Hub each time.

Point of this file: /NHNHOME survives container death (verified -- the
2026-09-08 container died and 2026-09-09 resumed from checkpoints on it), so
this is NOT a disaster-recovery inventory.  It exists so that a result in a
paper table can be traced to the exact weights that produced it, from
anywhere, without shell access to this machine.
"""
import csv, json, os, re, sys
from huggingface_hub import HfApi

LOG = '/NHNHOME/log-postech/doyoonkim/logs'
MODELS = '/NHNHOME/log-postech/doyoonkim/models'
BENCH = ['MATH', 'GPQA', 'IFEval', 'LCB', 'GSM8K']


def hub_models():
    """Index Hub repos by the run TIMESTAMP embedded in their name.

    Local dirs are gmp_s50pct_lr5e-05_onpol_lmda0.33_20260827_133259 while the
    Hub repo is cosmos1030/gmp-kd3e-1-s50pct-lr5e-5_20260827_133259 -- the
    prefixes differ (dashes, a kd tag, a different lr spelling), so a substring
    match on the directory name finds nothing. The 8+6 digit timestamp is the
    only part that survives both namings, and it is unique per run."""
    api = HfApi()
    out = {}
    for m in api.list_models(author='cosmos1030', limit=2000):
        t = re.search(r'(\d{8}_\d{6})', m.id)
        if t:
            out.setdefault(t.group(1), 'https://huggingface.co/' + m.id)
    return out


def main():
    hub = hub_models()
    rows = list(csv.DictReader(open(f'{LOG}/RESULTS_ALL.tsv'), delimiter='\t'))
    man = {}
    p = f'{LOG}/hf_archive_manifest.json'
    if os.path.exists(p):
        try:
            j = json.load(open(p))
            man = {k: v for k, v in j.items() if isinstance(v, dict)}
        except Exception as ex:
            print('manifest unreadable:', ex, file=sys.stderr)

    out = []
    for r in rows:
        ck = (r.get('ckpt') or '').strip()
        if not ck or r.get('state') != 'DONE':
            continue
        local = os.path.join(MODELS, ck)
        size = ''
        if os.path.isdir(local):
            n = sum(os.path.getsize(os.path.join(local, f))
                    for f in os.listdir(local)
                    if os.path.isfile(os.path.join(local, f)))
            size = '%.1f GB' % (n / 1e9)
        # a hub repo whose name embeds this run's directory, else manifest
        # Ground truth is the run's OWN log: --push_to_hub makes the trainer
        # print the repo it pushed to. Matching Hub repo names by the embedded
        # timestamp fails because the Hub name carries the UPLOAD time, not the
        # model directory's creation time (e.g. local ...20260907_194808 sits in
        # a repo named ...20260907_210125), so only 4 of 94 ever matched.
        url = ''
        lp = os.path.join(LOG, r['log'])
        if os.path.exists(lp):
            try:
                hits = re.findall(r'https://huggingface\.co/cosmos1030/[A-Za-z0-9._-]+',
                                  open(lp, errors='replace').read())
                for h in hits:
                    if '/tree/' not in h and '/blob/' not in h:
                        url = h.rstrip('.')
                        break
            except OSError:
                pass
        if not url:
            t = re.search(r'(\d{8}_\d{6})', ck)
            if t:
                url = hub.get(t.group(1), '')
        if not url and ck in man and man[ck].get('repo'):
            url = 'https://huggingface.co/' + man[ck]['repo']
        out.append(dict(label=r['label'], avg=r['avg5'],
                        **{b: r[b] for b in BENCH},
                        ckpt=ck, local_size=size,
                        on_hub=('yes' if url else 'NO'), url=url,
                        log=r['log']))
    out.sort(key=lambda x: (x['label'].split()[0], -float(x['avg'] or 0)))

    cols = ['label', 'avg'] + BENCH + ['on_hub', 'url', 'ckpt', 'local_size', 'log']
    with open(f'{LOG}/ARTIFACT_INDEX.tsv', 'w') as f:
        f.write('\t'.join(cols) + '\n')
        for r in out:
            f.write('\t'.join(str(r[c]) for c in cols) + '\n')

    up = [r for r in out if r['on_hub'] == 'yes']
    no = [r for r in out if r['on_hub'] != 'yes']
    with open(f'{LOG}/ARTIFACT_INDEX.md', 'w') as f:
        f.write('# Artifact index -- result -> weights -> URL\n\n')
        f.write('Auto-generated by `build_artifact_index.py`. %d finished runs '
                'with a saved checkpoint: **%d on the Hub, %d not yet**.\n\n'
                % (len(out), len(up), len(no)))
        f.write('The URL is the artifact; the local `ckpt` path is only a '
                'convenience. A container death leaves /NHNHOME intact, but a '
                'disk re-initialisation does not -- never treat a local path '
                'as durable.\n\n')
        for title, group in (('On the Hub', up), ('NOT on the Hub yet', no)):
            f.write('## %s (%d)\n\n| Run | Avg | %s | Weights |\n|---|---|%s|---|\n'
                    % (title, len(group), ' | '.join(BENCH), '---|' * len(BENCH)))
            for r in group:
                w = ('[%s](%s)' % (r['url'].split('/')[-1], r['url'])) if r['url'] \
                    else '`%s` (%s, local only)' % (r['ckpt'], r['local_size'])
                f.write('| %s | **%s** | %s | %s |\n'
                        % (r['label'], r['avg'],
                           ' | '.join(r[b] for b in BENCH), w))
            f.write('\n')
    print('ARTIFACT_INDEX: %d runs, %d on hub, %d missing' % (len(out), len(up), len(no)))


if __name__ == '__main__':
    main()
